#!/usr/bin/env python2.7

import sys
import argparse

from castalia import Castalia
from castaliaresultparser import CastaliaResultParser

def main():
     parser = argparse.ArgumentParser(description='a script for running and evaluating castalia simulations')
     parser.add_argument('-r', '--run', dest='run', default=False, const=True, action='store_const', help='run simulations')
     parser.add_argument('-c', dest='configuration', type=str, default="", action='store', help='a castalia configuarion to run')
     parser.add_argument('-i', dest='omnetpp_ini', type=str, default="omnetpp.ini", action='store', help='omnetpp.ini file which should be considered')
     parser.add_argument('-p', '--plot', dest='plot', default=False, const=True, action='store_const', help='plot simulation results')

     if len(sys.argv) == 1:
         parser.print_help()
         sys.exit(1)

     arguments = parser.parse_args()
     
     if arguments.run:
         if arguments.configuration != "" and arguments.omnetpp_ini != "":
             castalia = Castalia(arguments.configuration, arguments.omnetpp_ini)
             castalia.run()

     if arguments.plot:    
         if arguments.configuration != "" and arguments.omnetpp_ini != "":
             results = CastaliaResultParser()

if __name__ == "__main__":
    main()
